name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - uses: zbazztian/ghas-reports-action@v3.6
        with:
          token: ${{ secrets.ATOKEN }}
          repo: 'zbazztian/webgoat-demo'
          # optionally define repo (default is calling repo)

      - uses: actions/upload-artifact@v3.0.0
        with:
          name: results
          path: alerts.xlsx
